In [2]:
!pip install psycopg2-binary sqlalchemy pandas

Requirement already satisfied: psycopg2-binary in c:\users\thanq\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\thanq\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pandas in c:\users\thanq\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: greenlet>=1 in c:\users\thanq\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\thanq\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\thanq\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\thanq\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\thanq\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\thanq\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\thanq\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
engine = create_engine(
    "postgresql+psycopg2://postgres:123456@localhost:5432/banking"
)

In [5]:
df = pd.read_sql("SELECT * FROM accounts;", engine)

display(df)

   account_id  customer_id account_type   balance opened_date
0        5001         1001     Checking   3500.50  2020-03-15
1        5002         1001      Savings  12000.00  2020-03-16
2        5003         1002     Checking   2100.75  2019-07-22
3        5004         1003      Savings   8500.00  2021-01-10
4        5005         1004     Checking   4200.25  2020-11-05
5        5006         1004           CD  15000.00  2021-02-01
6        5007         1005     Checking   1800.00  2022-06-18
7        5008         1006      Savings  25000.00  2018-09-30

In [13]:
query = """
SELECT *
FROM accounts
WHERE account_type = 'Savings';
"""

df = pd.read_sql(query, engine)
display(df)

   account_id  customer_id account_type  balance opened_date
0        5002         1001      Savings  12000.0  2020-03-16
1        5004         1003      Savings   8500.0  2021-01-10
2        5008         1006      Savings  25000.0  2018-09-30

In [14]:
query = """
SELECT transaction_date, amount, transaction_type, last_name
FROM transactions
JOIN accounts
ON transactions.account_id = accounts.account_id
JOIN customers
ON accounts.customer_id = customers.customer_id
ORDER BY transaction_date;
"""

df = pd.read_sql(query, engine)
display(df)

  transaction_date  amount transaction_type last_name
0       2025-01-05   500.0          Deposit     Smith
1       2025-01-08   200.0       Withdrawal     Smith
2       2025-01-10  1000.0          Deposit     Smith
3       2025-01-12   150.0       Withdrawal   Johnson
4       2025-01-15   250.0          Deposit  Williams
5       2025-01-18   750.0          Deposit     Brown
6       2025-01-20   300.0          Deposit     Smith
7       2025-01-22   100.0       Withdrawal     Davis